1909-FLEX-GRACE-SHOPPER/TEAM-A

README.md
=> for review

.babelrc, .eslintrc.json, .gitignore, app/components/common/root.js, app/main.js, main.js, package.json, public/index.html, public/style.css, seed.js, server/api/index.js, server/db/index.js, server/index.js, webpack.config.js
Setting up the initial folders, adding config files like .babelrc
=> initial folders commit

db/models/order.js, db/models/price.js
Updated with Lachlan's feedback
=> updates to order and price models

db/index.js, db/models/order.js, db/models/orderitem.js, db/models/user.js, main.js, package-lock.json, package.json, seed.js
The seed function creates users, products, carts, orders, and adds random amounts of items to the latter two.
You can vary the number of records produced by editing the constants at the beginning of the file. 
During the process, I discovered a few changes to be made to the models -- mostly with validation rules, and also with the associations. Changing from hasOne to belongsTo just changes which model the foreignKey is on. 
Additionally, I removed the "total" field from the order model because it should be calculated from the associated items.
=> added seed function, minor tweaks to models

server/api/routes.md
Hey guys - please look over this routing plan in server/api/routes.md and provide any feedback. Thanks!
=> routes map

db/connection.js, main.js, package-lock.json, package.json, public/index.html, server/api/index.js, server/index.js
-Adds all the base routing to server/index
-updates main.js to start the server
-adds a few scripts
/api points to nothing right now, so navigating there will cause a crash
localhost:3000 will get you a hello world!
=> Server setup

package-lock.json, package.json, server/api/cart.js, server/api/index.js
CART: (/api/cart)
- create new cart (POST - '/')
- retrieve single cart, or all carts (GET - '/:cartId?')
- clear cart (PUT - '/:cartId')
=> Cart routes

server/api/cart.js, server/api/index.js, server/api/orderitem.js
POST 
-creates a new orderitem with the associated product and order
PUT
-allows for updating the orderitem quantity only
=> added orderitem route, update to cart route to fix bug

server/api/index.js, server/auth/index.js, server/auth/login.js, server/auth/logout.js, server/auth/who.js, server/index.js
-logout route
-login route (needs actual POST method with hashing written)
-who route, which will be used by the framework to return the currently logged in user
We will also need to add a sessionId column to the User model and update the route to PUT on that. I'll do that in a subsequent PR
=> added pieces of routes for authentication

db/models/user.js, package.json
-adds a sessionId text field to the user model
-validation is minimal now because I need to think more on if it makes sense for it to be null
=> update to userId model to add sessionId for auth

db/index.js, package-lock.json, package.json, server/api/index.js, server/api/order.js, server/api/user.js, server/utils.js
User route provides
GET:
-Return a flat list of all users
-Return a single user by ID, including cart and all order 
PUT:
-updates sessionId only at this point. We can enable more editing as needed
POST:
-special post to /user/guest generates a guest user (requires no request body content)
-post to regular /user generates user with required fields firstName, lastName, email, and password. _I'm not sure if it's more secure to hash the password on the frontend and then send it, or hash it on the server side._ 
TODO in future PR:
-write a more secure function for generating the sessionId
-drop in the password hashing function
=> added user routes and more authentication framework

server/api/cartItem.js, server/api/index.js
cart item routes (/api/cartitem)
POST ('/')
- creates new CartItem, returns created CartItem along with associated Product
GET ('/:cartItemId?')
- retrieves all CartItems, or single CartItem if given a cartItemId
PUT ('/:cartItemId')
- edits CartItem of given cartItemId, returns edited CartItem
DELETE ('/:cartItemId')
- deletes CartItem of given cartItemId
=> Cart item routes

package-lock.json, package.json
=> fix issue with package lock

package-lock.json, package.json
=> package-lock-fix

db/models/user.js, seed.js
-Added unique constraint to email field in user model, since this is what we search by for auth and login
-Updated seed file to reflect this. It now only generates registered users.
=> Seed file + user model update

app/components/common/root.js, app/components/common/testAuthPage.js, app/components/index.js, app/redux/user.js, server/api/user.js, server/auth/login.js
-on component mount, the component will:
-check if a user exists in the store
-if not, generate a guest
-set the user in the store to the guest
-set the cookie on the page to the guest's sessionId
=> Auth thunks

app/components/components.md
updates made (e.g. 'order success' component)
=> Components map

app/components/common/root.js, app/components/common/testAuthPage.js, app/components/index.js, app/components/login/LoginPage.js, app/redux/user.js, package-lock.json, package.json, server/auth/login.js
-added basic functionality so a user can enter email and password, it will be validated against the DB, and they will be logged in or rejected
-if logged in, cookie will set on their browser
=> Login page

app/components/SingleProduct.js, app/components/common/root.js, app/components/components.md, app/components/index.js, app/redux/cart.js, app/redux/order.js, app/redux/user.js, db/models/user.js, package-lock.json, seed.js, server/api/cart.js, server/api/products.js, server/api/user.js, server/auth/login.js
single product page added, "add to cart" functionality, User model updated with `password` column instead of `hashedPassword` for clarity and consistency.
Please run `npm seed` to reset database with new columns!
=> Single product page, add to cart functionality, User model updated

app/components/common/testAuthPage.js, app/components/login/LoginPage.js, app/redux/index.js, db/models/shippingaddress.js
some updates including fixes for incorrect file names in imports from my last PR
=> Some minor fixes

app/components/login/LoginPage.js, app/redux/user.js, server/auth/login.js
-Minor updates to routes to make the login flow work better
-dynamically redirects to home once the user is logged in
=> minor logic updates and dynamic redirect

app/components/checkout/AddressForm.js, app/components/checkout/Checkout.js, app/components/checkout/PaymentForm.js, app/components/checkout/Review.js, app/components/common/root.js, app/components/components.md, app/components/index.js
**To TEST UI flow after starting server go to** ===>> **http://localhost:3000/#/checkout**
-----------------------------------------------------------------------------------------------
Changes done:
1) added checkout module with 4 screens built using material UI. COMPLETE BACKEND integration is pending but full UI has been made and tested.
2) code is in app/components/checkout. 4 new files:
 - addressform.js
 - checkout.js
 - paymentform.js
 - review.js (after order submit)
few other files modified: components/common/root.js and components/index.js
3) To check UI flow after starting server go to http://localhost:3000/#/checkout
4) Once backend route is created by Lachlan i will integrate it and add backend integration
=>  added checkout module in frontend

server/api/index.js, server/api/shippingAddress.js
routes added for shipping address (POST, PUT, GET) - no DELETE yet
=> Shipping Address routes

db/models/product.js
-it has a default value set in the model, so no need to change any routes/etc
=> added imageURL field to product

app/components/Navbar.js, app/components/common/root.js, app/redux/user.js
-if you login as a user, then refresh, your login will stay
-if a guest is created, the same guest will stay set despite refresh
=> updates to redux and root to make a login preserve

app/components/Cart.js, app/components/Home.js, app/components/Navbar.js, app/components/common/root.js, app/components/login/LoginPage.js, app/redux/cart.js, app/redux/user.js, server/api/cart.js
- cart in navbar now auto-updates according to number of items
- added thunk & route to GET cart by userId
=> navbar cart dynamic functionality

app/components/Cart.js, package-lock.json
=> products render in cart

app/components/Cart.js, app/components/SingleProduct.js
added checkout button, quantity updatable and delete buttons to cart page
=> Cart updates

app/redux/cart.js, app/redux/user.js, db/index.js, db/models/index.js, db/models/session.js, db/models/user.js, server/api/cart.js, server/auth/login.js, server/auth/who.js, server/index.js
Alright boys, here's the big one.
-Cart API routes and thunks modified to allow for sessionId as a key. 
-User thunks modified to eliminate guests
-Session table added
-Server index updated to add a sessionId cookie to all requests
-Server index updated to search for and add a user based on all requests 
-Login modified to update a user's sessionId on login
=> added session table, updated various routes and thunks

app/components/AccountInfo.js, app/components/Navbar.js, app/components/components.md, app/components/index.js, app/components/login/LoginPage.js, app/redux/cart.js, app/redux/order.js, app/redux/user.js, server/api/orderitem.js
- fixed login route
- fixed navbar bugs
- added Alex's fixes for login flicker bug
- logout functionality still needs fixing (low priority for rn)
=> small bugfixes

app/redux/cart.js, db/index.js, db/models/user.js, server/auth/who.js
Just a few changes to help with debugging:
-the /who api doesn't return 404 when no user is found anymore, just null
-added User.hasMany(ShippingAddress)
-removed isRegistered from User model, replaced with isAdmin which defaults to false
=> updated user model, minor changes to improve debugging

app/components/AllOrders.js, app/components/common/root.js, app/redux/cart.js, db/index.js, server/api/cart.js, server/api/order.js
Fixes to cart thunks and routes so that cart is created & set successfully for guest. (Checkout process still failing for guest, will get to that next)
=> cart thunk fixes

app/components/login/LoginPage.js, app/redux/cart.js, server/api/cart.js, server/api/cartItem.js, server/api/shippingAddress.js
Guest cart now merges into existing user cart on login, via `mergeCart` thunk
Session cart is deleted after merge complete
=> Cart merge fix

constants.js, db/models/product.js, seed.js, server/api/products.js, server/utils.js
- Product categories added to `constants.js`, and worked into `Product` model and `seed.js`
- `cat` (category) query added to `products` GET route
=> Categories

.travis.yml, db/connection.js, package.json
-Added yaml config for travis
-tweaks to test script, etc
=> travis CI integration

tests/01-routes.js, tests/02-models.js
-included product category into tests
=> included product category in test

app/components/EditProduct.js, app/redux/products.js, server/api/products.js
-an admin user can delete a product from the dit page
-added delete product thunk
-styling improvements
=> added delete to product edit page; styling updates

seed.js, server/api/user.js, server/auth/login.js
-Any new users created via POST will have their passwords stored as hashed
-Seed updated to reflect this too
=> added hashing back to API routes

app/components/Pagination.js, app/components/ProductsList.js, app/redux/products.js, server/api/products.js
-added support to thunk for a page and category
-updated route to handle page number in request
=> Pagination backend support

app/components/AccountInfo.js, app/components/login/LogoutButton.js, app/redux/user.js, server/auth/logout.js
-Logout route fixed
-Logout thunk fixed
-Logout button now appears in the account info page. It makes a POST to /auth/logout
=> fixed logout issues, added button back to account info page

seed.js
-images correspond to category and have random colors :)
=> updated seed to use better images

app/components/login/NewUserRegistration.js, app/redux/user.js, server/api/user.js
- during signup check if user entered email exists in DB
- if yes dont allow user to sign up, display message: "Signup failed
Email already exists, please login or use different email to signup."
- changed 3 files: 
1) user POST api changed to handle isUnique constraint handling by doing user search on entered emailid, if user found return res status set to 400 with error message, else proceed with new user creation in DB  
2) redux : user set to null , if email exists
3) NewUserRegistration.js: handle submit to setError if user is set null due to same email found, then display signUpError title and message using ErrorBar functional component
=> Registration email error handling, if exists

app/components/Pagination.js, app/components/ProductsList.js
-created the component
-put in products list page
-increments appropriately, but doesn't make any thunk calls yet
=> Pagination frontend

app/components/Pagination.js, app/redux/count.js, app/redux/index.js, package-lock.json, server/api/products.js
-added an extra condition/query param to the products route to have a way to get ALL products
-added an extra redux reducer to hold the total count of all products. Yes, this could have been factored into the existing products store but I didn't want to break everything. This solution had no impact to the rest of the project.
-pagination now works in the frontend
=> Pagination backend

app/components/ProductReview.js, app/components/ProductsList.js, app/components/SingleOrder.js, app/components/SingleProduct.js, app/components/SuccessBar.js, app/components/common/root.js, app/components/index.js, app/components/styles/useStyles.js, app/redux/ordersByUser.js, app/redux/rating.js, app/redux/review.js, db/index.js, db/models/product.js, db/models/review.js, server/api/products.js, server/api/review.js, stripeConfig.js
**NB: Still some mergeCart errors from previous dev merges that need to be fixed**
- `Product` model updated to include `numRatings` and `averageRating` columns
- `Review` model updated to include `title` and `body` columns
- `Review/Product/User` associations updated (reviews are connected to both `user` & `product`)
- On selecting "View Orders" on account info page, past orders are listed. On selecting an order, order items are displayed. Option to leave a review for product.
- Reviews & Ratings functionality is connected to `selectedProduct` on state, so that a user is prevented from just going to a URL to leave a review for a product they haven't purchased (e.g. `/review/29`). If `selectedProduct` is empty, review/ratings functionality will display errors.
- An admin cannot add a …
=> review & ratings backend functionality added

app/components/SingleProduct.js
-shows the reviews on singleProduct page.
=> Display review

app/components/ProductsList.js, app/redux/products.js, server/api/products.js
- search field on ProductsList page updates products on input change, using `val` query (case insensitive)
=> added product search functionality using val query

.gitignore, app/components/checkout/CardSection.js, app/components/checkout/Checkout.js, app/components/checkout/PaymentForm.js, app/components/checkout/Review.js, app/components/checkout/StripePaymentForm.js, app/main.js, main.js, package-lock.json, package.json, public/index.html, server/api/checkout.js, server/api/index.js, server/index.js, webpack.config.js
=> Stripe redo

app/components/SingleProduct.js, package-lock.json, seed.js
=> Seed rating

app/components/Cart.js, app/components/Navbar.js, app/components/SingleProduct.js, app/components/checkout/Review.js, package-lock.json, server/api/order.js
- update order route to change default sort to DESC
-fix the wonky checkout review page
-change product review layout on review page to look like a quote “” or italics
-Change store name to SLEEK UNBRANDED STORE
=> usability fixes

app/components/SingleProduct.js
-remove link to leave a review
-shows 'No Reviews' if there are no reviews
-removed a console.log
=> Single product fixes
